### ISSUE TITLE
HTTPError again

### ISSUE THREAD

**Issue by Beppe23** [louis-haddrell/Yik-Yak-API#13]
Hey, thanks for making this! I know you already answered a similar question but using the fixes that you posted there it still isn't working. When I try to run my code I get the following error:

``` File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://www.yikyak.com/api/auth/initPairing
```

The code that I am running in my yakbot.py is: 

'''from yikyakapi.web import WebObject
from yikyakapi.yikyak import YikYak

```web = WebObject()
COUNTRY_CODE = "CAN"
PHONE_NUMBER = "XXXXXXXXXX"

if __name__ == "__main__":
	client = YikYak()
	pin = input("Web authentication PIN: ")
	client.login_id(COUNTRY_CODE, PHONE_NUMBER, pin)

user_id = client.yakker.user_ID
print("User ID: ", user_id)

USER_ID = 'JumboVibes'
client.login_id(COUNTRY_CODE, PHONE_NUMBER, USER_ID)

yaks = client.get_new_yaks(xx.xxxxxx, -xxx.xxxxxx)
print("Yaks: ")
for key in yaks:
	print(yaks)

client.compose_yak("Hello world!", xx.xxxxxx, -xxx.xxxxxx) 
```
The 500 internal service error makes me think that this is a problem with YikYaks API endpoints and not in the code itself? Any suggestions for how to get this working again? Thanks!

**Comment by louis-haddrell** [comment]
I've just pushed a commit to hopefully make the login process a little clearer.

For your first login, you should be using `login_pin()`:

```python
client = YikYak()
pin = input("Web authentication PIN: ")
client.login_pin(COUNTRY_CODE, PHONE_NUMBER, pin)
```

Once you've logged in, you can print out your user ID. There's a small typo in your code - it should be:

```python
print("User ID: ", client.yakker.userID)
```

Once you've got that ID, you use `login_id()` to login without needing the PIN code again. Make sure that you're using that ID, not your YikYak username. It should be a 32 character string:

```python
USER_ID = '0123456789ABCDEF0123456789ABCDEF'
client.login_id(COUNTRY_CODE, PHONE_NUMBER, USER_ID)
```

Hope that helps! :)

**Comment by Beppe23** [comment]
Thanks for the quick response! That helped for getting the user ID, then when I ran your code in the README.md to post a yak the following occurs 
```
Web authentication PIN: 852114
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10e6e3710>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.yikyak.com', port=443): Max retries exceeded with url: /api/auth/initPairing (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10e6e3710>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```
Any idea why this might still be occurring? I downloaded the updated .zip file so everything should be up to date... Thanks!

**Comment by louis-haddrell** [comment]
From what I can tell, it seems to be a connection issue unrelated to the API code. Are you able to use the YikYak website without issue?

**Comment by Beppe23** [comment]
Yes, I can view the feed perfectly.

**Comment by louis-haddrell** [comment]
What happens if you try to access the site with Python?

```python
import requests
requests.get("https://www.yikyak.com/api/auth/initPairing")
```
