### ISSUE TITLE
Unable to authenticate - 500 Internal Server Error

### ISSUE THREAD

**Issue by scizzorz** [louis-haddrell/Yik-Yak-API#3]
I just found this and it looks phenomenal, but I'm having trouble authenticating. Here's what I've tried:

```
>>> from yikyak import yikyak
>>> s = yikyak.YikYak()
>>> s.login('USA', '1607-------', '------')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/john/dev/yikyak2/yikyak/yikyak.py", line 30, in login
    self.auth_token = self.pair(country_code, phone_number, pin)
  File "/home/john/dev/yikyak2/yikyak/yikyak.py", line 79, in pair
    response = self._request('POST', url, json=json)
  File "/home/john/dev/yikyak2/yikyak/web.py", line 54, in _request
    response.raise_for_status()
  File "/home/john/dev/yikyak2/env/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://www.yikyak.com/api/auth/pair
```

Is there some special format for the phone number or a list of valid country codes or any other reason why this wouldn't work?

Thanks!

**Comment by scizzorz** [comment]
Ah, `'US'` works.

**Comment by louis-haddrell** [comment]
Glad to see you got it working - I've also now added a list of countries and their codes into the README :smile:
