### ISSUE TITLE
Unable to refresh auth token?

### ISSUE THREAD

**Issue by scizzorz** [louis-haddrell/Yik-Yak-API#4]
When I try to refresh my auth token, I get this error:

```
WARNING:root:Failed to decode JSON from response
Traceback (most recent call last):
  File "yaks.py", line 28, in <module>
    get_new_yaks()
  File "yaks.py", line 16, in get_new_yaks
    yaks = client.get_new_yaks(auth['lat'], auth['long'])
  File "/home/john/dev/yikyak2/yikyak/yikyak.py", line 124, in get_new_yaks
    return self._get_yaks(url, latitude, longitude)
  File "/home/john/dev/yikyak2/yikyak/yikyak.py", line 105, in _get_yaks
    response = self._request('GET', url, params=params)
  File "/home/john/dev/yikyak2/yikyak/web.py", line 45, in _request
    response = requests.request(method, url, **kwargs)
  File "/home/john/dev/yikyak2/env/lib/python3.5/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/john/dev/yikyak2/env/lib/python3.5/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/john/dev/yikyak2/env/lib/python3.5/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/john/dev/yikyak2/env/lib/python3.5/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/home/john/dev/yikyak2/env/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/home/john/dev/yikyak2/env/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1123, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.5/http/client.py", line 1059, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object
```

Is there any reason this might happen?

Also, is there any knowledge about how frequently an auth token needs to be refreshed?

**Comment by louis-haddrell** [comment]
Cheers for spotting this. Issue should be fixed by 245e0a5c6a0e5136ef476d38a1bbc8ff98e31726

I'm not currently sure about how frequently the auth token needs to be refreshed, but this is something I will look into.

I intend at some point to make the token automatically refresh once it has expired.
